### PR TITLE
Force simbank manager to use 0.13.0 of osgi.annotations

### PR DESCRIPTION
**Pull request by hobbit1983**

### CODE REVIEW

**Comment by hobbit1983** [comment]
Asking @Michael-Baylis to sanity check that I have drawn the line correctly when re-versioning and I've not missed anything

**Comment by hobbit1983** [comment]
fixes galasa-dev/projectmanagement#885

**Review by Michael-Baylis — APPROVED** [review]

**Comment by hobbit1983** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
rerun tests

**Pull request merged**
