### PR TITLE
mcobbett bump galasa maven plugin

### PR DESCRIPTION
**Pull request by techcobweb**
- bump version of maven plugin, add build-locally script to build docker file
- remove unwanted warnings in the code

### CODE REVIEW

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Comment by galasa-team** [comment]
Build successful

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
